# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trilith_pb2 as trilith__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trilith_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextManagerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Write = channel.unary_unary(
                '/trilith.ContextManager/Write',
                request_serializer=trilith__pb2.WriteRequest.SerializeToString,
                response_deserializer=trilith__pb2.WriteAck.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/trilith.ContextManager/Query',
                request_serializer=trilith__pb2.QueryRequest.SerializeToString,
                response_deserializer=trilith__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Assemble = channel.unary_unary(
                '/trilith.ContextManager/Assemble',
                request_serializer=trilith__pb2.AssembleRequest.SerializeToString,
                response_deserializer=trilith__pb2.AssembledContext.FromString,
                _registered_method=True)
        self.Forget = channel.unary_unary(
                '/trilith.ContextManager/Forget',
                request_serializer=trilith__pb2.ForgetRequest.SerializeToString,
                response_deserializer=trilith__pb2.ForgetAck.FromString,
                _registered_method=True)


class ContextManagerServicer:
    """Missing associated documentation comment in .proto file."""

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Assemble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=trilith__pb2.WriteRequest.FromString,
                    response_serializer=trilith__pb2.WriteAck.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=trilith__pb2.QueryRequest.FromString,
                    response_serializer=trilith__pb2.QueryResponse.SerializeToString,
            ),
            'Assemble': grpc.unary_unary_rpc_method_handler(
                    servicer.Assemble,
                    request_deserializer=trilith__pb2.AssembleRequest.FromString,
                    response_serializer=trilith__pb2.AssembledContext.SerializeToString,
            ),
            'Forget': grpc.unary_unary_rpc_method_handler(
                    servicer.Forget,
                    request_deserializer=trilith__pb2.ForgetRequest.FromString,
                    response_serializer=trilith__pb2.ForgetAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trilith.ContextManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trilith.ContextManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextManager:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trilith.ContextManager/Write',
            trilith__pb2.WriteRequest.SerializeToString,
            trilith__pb2.WriteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trilith.ContextManager/Query',
            trilith__pb2.QueryRequest.SerializeToString,
            trilith__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Assemble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trilith.ContextManager/Assemble',
            trilith__pb2.AssembleRequest.SerializeToString,
            trilith__pb2.AssembledContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trilith.ContextManager/Forget',
            trilith__pb2.ForgetRequest.SerializeToString,
            trilith__pb2.ForgetAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
